### ISSUE TITLE
Unable to long press an webelement using version 1.5.0.3, works in 1.5.0.2

### ISSUE THREAD

**Issue by moliveras** [serhatbolsu/robotframework-appiumlibrary#247]
I have a robotframework keyword "Delete All Text Messages" which deletes all text conversation on an android phone from the mesaging app. I am using keyword "Get Web Elements" to identify all of the conversations with "id=com.google.android.apps.messaging:id/conversation_name" and then iterating in a FOR loop to long press each element - something like this:

@{conversations}    Get Web Elements id=com.google.android.apps.messaging:id/conversation_name
    : FOR    ${conversation}    IN    @{conversations}
    \    Long Press    ${conversation}    300

This works just fine up until robotframework-appiumlibrary 1.5.0.2.

After upgrading to 1.5.0.3, the Get Web Elements works, however when I try to Long press on an element in the list it fails with:
"FAIL : AttributeError: 'list' object has no attribute 'id'"

Downgrading back to version 1.5.0.2 resolves the issue.  If any additional information if needed please let me know and I will attach it.

**Comment by idxn** [comment]
@serhatbolsu  This was the same issue as mine and it's fixed in my pull request #246

**Comment by serhatbolsu** [comment]
Closed with 1.5.0.4
