### ISSUE TITLE
IOS 13 support: Test is giving error 'NoneType' object has no attribute 'send_keys' when trying to type in a UIATextField

### ISSUE THREAD

**Issue by parinita-rao** [serhatbolsu/robotframework-appiumlibrary#259]
**[Environment]**
Simulator : iPhone 8 
iOS:13.0
appium: appium@beta
robotframework-appium library version: 1.5.0.4

pip list
Package                         Version  
------------------------------- ---------
allure-python-commons           2.7.1    
allure-robotframework           2.7.1    
Appium-Python-Client            0.46     
asn1crypto                      0.24.0   
attrs                           19.1.0   
backports.functools-lru-cache   1.5      
bcrypt                          3.1.7    
beautifulsoup4                  4.8.0    
certifi                         2019.6.16
cffi                            1.12.3   
chardet                         3.0.4    
configparser                    3.8.1    
contextlib2                     0.5.5    
cryptography                    2.7      
cx-Oracle                       7.2.2    
DateTime                        4.3      
decorator                       4.4.0    
dill                            0.3.0    
docutils                        0.15.2   
enum34                          1.1.6    
Faker                           2.0.0    
futures                         3.3.0    
glance-dom                      0.11.5   
holidays                        0.9.11   
ibm-db                          3.0.1    
idna                            2.8      
importlib-metadata              0.19     
ipaddress                       1.0.22   
jsonpatch                       1.16     
jsonpointer                     1.10     
kitchen                         1.2.6    
libxml2dom                      0.5      
lxml                            4.4.1    
mss                             4.0.3    
multiprocessing                 2.6.2.1  
mysql-connector-python          8.0.17   
natsort                         6.0.0    
numpy                           1.16.4   
opencv-python                   4.1.0.25 
paramiko                        2.6.0    
pathlib2                        2.3.4    
Pillow                          6.1.0    
pip                             18.1     
pluggy                          0.12.0   
port-for                        0.4      
protobuf                        3.9.1    
pyasn1                          0.4.6    
pyasn1-modules                  0.2.6    
pycparser                       2.19     
pycrypto                        2.6.1    
PyMySQL                         0.9.3    
PyNaCl                          1.3.0    
pyPdf                           1.13     
python-dateutil                 2.8.0    
python-ldap                     3.2.0    
python-tds                      1.9.1    
pytz                            2019.2   
reportlab                       3.5.23   
requests                        2.22.0   
robotframework                  3.1.2    
robotframework-appiumlibrary    1.5.0.4  
robotframework-csvlibrary       0.0.2    
robotframework-databaselibrary  1.2.4    
robotframework-excellibrary     0.0.2    
robotframework-faker            4.2.0    
robotframework-httplibrary      0.4.2    
robotframework-pabot            0.84     
robotframework-requests         0.5.0    
robotframework-screencaplibrary 1.3.0    
robotframework-selenium2library 3.0.0    
robotframework-seleniumlibrary  3.3.1    
robotframework-sshlibrary       3.3.0    
robotframework-sudslibrary      0.8      
robotremoteserver               1.1      
scandir                         1.10.0   
scp                             0.13.2   
selenium                        3.141.0  
setuptools                      40.6.2   
simple-crypt                    4.1.7    
simplejson                      3.16.0   
six                             1.12.0   
soupsieve                       1.9.3    
sshtunnel                       0.1.5    
suds                            0.4      
text-unidecode                  1.2      
unicodecsv                      0.14.1   
urllib3                         1.25.3   
waitress                        1.0.2    
WebOb                           1.7.3    
WebTest                         2.0.28   
wheel                           0.33.6   
wrapt                           1.11.2   
xlrd                            1.2.0    
xlutils                         2.0.0    
xlwt                            1.3.0    
xml2json                        1.1      
xmljson                         0.2.0    
xmltodict                       0.12.0   
zipp                            0.5.2    
zope.interface                  4.6.0 

On trying to input text inside a UIATextField, The test throws the following error
AttributeError: 'NoneType' object has no attribute 'send_keys'

The same test is working fine with iOS 12.1 + appium 1.4.0

**Comment by serhatbolsu** [comment]
I will be able to test this next week

**Comment by serhatbolsu** [comment]
I have heard that identifier in IOS12 might not work in IOS13 since field identified might be returning more then 1 object now. Try to update your object identifier, verify that it is just 1 object returned with appium inspector
